### ISSUE TITLE
Explain VITE_BOTPRESS_BOT_ID_AS_USER variable

### ISSUE THREAD

**Issue by Satellite-system** [devguilhermy/botpress-inbox#2]
You have mentioned VITE_BOTPRESS_BOT_ID_AS_USER variable to be included in .env file, can you please help me from where could I find this variable value..?
You have not mentioned how to obtain this variable, please mention that too, in the readme file.

**Comment by devguilhermy** [comment]
Hey @Satellite-system, sorry for the late response.
Yeah that was in the instructions already haha
