### ISSUE TITLE
Commande NPM

### ISSUE THREAD

**Issue by chirelhalioua** [devguilhermy/botpress-inbox#3]
Bonjour, 

merci pour votre projet, lorsque j'essaie de lancer ce projet dans le cmd je reçois ce message : 

![image](https://github.com/devguilhermy/botpress-inbox/assets/72791846/65eddbc5-8f0b-45e5-8300-4fc1dacc88b7)

merci pour votre aide

**Comment by devguilhermy** [comment]
Hey @chirelhalioua, you need to run `npm install` first!

I will update the instructions with this information!
Sorry for that, and thanks for reporting!

**Comment by chirelhalioua** [comment]
Merci, mais j'ai toujours le même message
